### ISSUE TITLE
Configuration is permitted  when interfaces is missing from INF object

### ISSUE THREAD

**Issue by pbmoses** [openshift/ingress-node-firewall#444]
**Describe the bug**
An IngressNodeFirewall object is allowed even if interfaces is left out of the manifest, despite the CRD which states minItems: 1 for interfaces. In turn this leads to a failure, as the error can be seen in the IngressNodeFirewallState but the INF status simply states `syncStatus: Error` which can lead to confusion on the user/admin end. 

Same process can be seen in Ingress config, where it is admitted without proper config,  despite MinItem:1 in CRD

INF Manifest
![Screenshot 2023-11-20 at 11 41 33 AM](https://github.com/openshift/ingress-node-firewall/assets/24865328/ab42b50a-4320-44ff-b6b7-2e89d59eb526)

IngressNodeFirewallState
```
status:
  syncErrorMessage: Invalid interface name - cannot provide an empty list
  syncStatus: Error
```
![Screenshot 2023-11-20 at 11 42 57 AM](https://github.com/openshift/ingress-node-firewall/assets/24865328/a3607347-f6a7-4599-89d1-eeace23f62a0)

CRD
ingressnodefirewalls.ingressnodefirewall.openshift.io
```
                interfaces:
                  description: >-
                    interfaces is a list of interfaces where the ingress
                    firewall policy will be applied on.
                  type: array
                  minItems: 1
                  items:
                    type: string
```
In the controller this is handled:
```
			// Now, iterate over all interfaces in the InrgessNodeFirewallSpec.
			if len(firewallObj.Spec.Interfaces) == 0 {
				state.Status = infv1alpha1.IngressNodeFirewallNodeStateStatus{
					SyncStatus:       infv1alpha1.SyncError,
					SyncErrorMessage: "Invalid interface name - cannot provide an empty list",
				}
				// Write back the state to the map and then continue with the next node.
				nodeStates[node.Name] = state
				continue withNextNode
			}
```
Possibly the `omitempty` is taking precedence here:
```
	// interfaces is a list of interfaces where the ingress firewall policy will be applied on.
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinItems:=1
	Interfaces []string `json:"interfaces,omitempty"`
```
https://github.com/openshift/ingress-node-firewall/blob/12da1395940541a4e9696cb599b72cd04ec4288d/api/v1alpha1/ingressnodefirewall_types.go#L160

**To Reproduce**
1. Install IngressNodeFirewallOperator
2. Create IngressNodeFirewallConfig
3. Create IngressNodeFirewall but do not include `interfaces` array
4. See errors above

**Expected behavior**
If interfaces are omitted, deny creation of the IngressNodeFirewall object to avoid any confusion on the user/admin end.  As it is currently implemented, an expected failure occurs with the IngressNodeFirewall and the user/admin is left to track the failure via the state.

**Comment by msherif1234** [comment]
Thanks @pbmoses for opening this issue I will investigate and fix

**Comment by pbmoses** [comment]
I actually have it fixed I believe but am in the final testing stage (accidentally submitted PR then cancelled.) The same also seems to be true for ingress config

**Comment by msherif1234** [comment]
early on we were thinking of using empty list to enable on all interfaces but we decided half way to be very specific and include all involved interfaces to avoid any harm with that having `omitempty` in this field is not valid

**Comment by msherif1234** [comment]
for the config I think you are referring to rule like this which is valid 
```yaml
 ingress:
  - sourceCIDRs:
       - 172.16.0.0/12
    rules:
    - order: 10
      action: Deny
```
pls confirm is this what u were referring to ?
